//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tinyplay.rc
//
#define IDSELECT                        10
#define IDI_PLAYWND                     100
#define IDR_MENU                        101
#define IDC_BRIGHTNESS                  101
#define IDR_ACCELERATOR1                102
#define IDC_CONTRAST                    102
#define IDC_SATURATION                  104
#define IDC_HUE                         105
#define IDD_RATE                        106
#define IDC_GAMMA                       106
#define IDD_JUMP                        107
#define IDD_COLORS                      108
#define OPTIONS_START                   110
#define OPTIONS_GENERAL                 111
#define OPTIONS_PLAYLIST                112
#define OPTIONS_AUDIO1                  113
#define OPTIONS_AUDIO2                  114
#define OPTIONS_VIDEO                   115
#define OPTIONS_SUBTITLES               116
#define OPTIONS_CD                      117
#define OPTIONS_LOCALCDDB               118
#define OPTIONS_CDDB                    119
#define IDD_SUBTTIME                    120
#define IDD_KEYS                        121
#define IDD_CD                          122
#define IDD_URL                         123
#define IDD_MULTCD                      124
#define IDD_SITES                       125
#define IDD_AUDIO_FILTER                127
#define IDB_PLAYBTN                     129
#define IDC_MENUDROP                    130
#define IDC_KEY                         131
#define IDD_DDCOLOR                     131
#define IDC_TICK                        132
#define IDC_EXTENSIONS                  133
#define IDC_FREEDB_PORT                 134
#define IDC_FREEDB_PATH                 135
#define IDC_COLUMNS                     136
#define IDC_AUDIO_OUT                   137
#define IDC_RATE                        138
#define IDC_JUMP                        139
#define IDC_JUMPSEC                     140
#define IDC_DS_FORMAT                   141
#define IDC_DS_SAMPLE_SIZE              142
#define IDC_DS_UNDERRUN                 143
#define IDC_DS_LOCKS                    144
#define IDC_DS_BUFFERED                 145
#define IDC_EMAIL                       146
#define IDC_FREEDB_SERVER               147
#define IDC_OPENDIR_FOLDER              148
#define IDC_DSTRACK_PREBUF              149
#define IDC_DSPREBUF                    150
#define IDC_SUBTDIR                     151
#define IDC_OVERLAP                     152
#define IDC_URL                         153
#define IDC_SUBTEXT                     154
#define IDC_CDDBFOLDER                  155
#define IDC_PROXY_USER                  156
#define IDC_PROXY_PASS                  157
#define IDC_DSNOTIF_POS                 158
#define IDC_DSBUFLEN                    159
#define IDC_SITELIST                    160
#define IDC_PROXY                       161
#define IDC_PROXYPORT                   162
#define IDC_MULTRESULT                  163
#define IDC_REVISION                    164
#define IDC_FREEDB_TIMEOUT              165
#define IDC_EQ_FREQ                     166
#define IDC_SUBTSHIFT                   167
#define IDC_ASSOCIATED                  168
#define IDC_VISTIMER                    169
#define IDC_SUBTDELAY                   170
#define IDC_CDSPEED                     171
#define IDC_KEYCMD                      172
#define IDC_SUBTSCALE                   173
#define IDC_CDSECTORS                   174
#define IDC_CDMETHOD                    175
#define IDC_BROWSE                      176
#define IDC_DSSLEEP                     177
#define IDC_TOTAL                       179
#define IDC_CDARTIST                    180
#define IDC_CDALBUM                     181
#define IDC_CDORDER                     182
#define IDC_CDEXTD                      183
#define IDC_CDYEAR                      184
#define IDC_CDGENRE                     185
#define IDC_CDCATEGORY                  186
#define IDC_CDLIST                      187
#define IDC_DISCID                      188
#define IDC_MEDIAID                     189
#define IDC_DEFAULT_ORDER               190
#define IDC_PRIORITYCOMBO               191
#define IDC_VISUALPRIORITYCOMBO         192
#define IDC_SAVEDLIST                   193
#define IDC_TITLE                       194
#define IDC_CDSPEED_INTERVAL            195
#define IDD_ABOUTBOX                    200
#define ID_FILE_OPENCLIP                201
#define ID_FILE_EXIT                    202
#define ID_FILE_PAUSE                   203
#define ID_FILE_STOP                    204
#define ID_SHOW_CURRENT                 205
#define ID_REPEAT_STOP                  206
#define ID_FILE_FULLSCREEN              207
#define ID_FILE_SIZE_NORMAL             208
#define ID_FILE_SIZE_HALF               209
#define ID_FILE_SIZE_DOUBLE             210
#define ID_FILE_SIZE_THREEQUARTER       212
#define ID_FILE_PLAY                    213
#define ID_SOUND_WAV                    214
#define ID_SOUND_STEREO                 215
#define ID_SOUND_MONO                   216
#define ID_SOUND_LEFT                   217
#define ID_SOUND_RIGHT                  218
#define ID_SOUND_MUTE                   219
#define ID_RATE_INCREASE                220
#define ID_RATE_DECREASE                221
#define ID_RATE_NORMAL                  222
#define ID_RATE_DOUBLE                  223
#define ID_RATE_HALF                    224
#define ID_SINGLE_STEP                  225
#define ID_FILE_PREVIOUS                227
#define ID_FILE_NEXT                    228
#define ID_PLAYLIST_REMOVE              229
#define ID_HELP_ABOUT                   230
#define ID_REPEAT                       231
#define ID_ZOOMIN                       232
#define ID_ZOOMOUT                      233
#define ID_FILE_SIZE_150                234
#define ID_DELETEINI                    235
#define ID_RATIO34                      237
#define ID_RATIO169                     238
#define ID_RATIO_ORIG                   239
#define ID_ONTOP                        240
#define ID_REFRESH                      241
#define ID_SHUFFLE                      242
#define ID_RANDOM                       243
#define ID_OPENDIR                      244
#define ID_OPTIONS                      245
#define ID_PLAYLIST_SELECTALL           247
#define ID_PLAYLIST_REMOVEALL           248
#define ID_PLAYLIST_REVERSE             249
#define ID_PLAYLIST_INVERTSELECTION     250
#define ID_UNSELECTALL                  251
#define ID_HELP_README                  252
#define ID_CONTROL_JUMPFORWARD          253
#define ID_CONTROL_JUMPBACKWARD         254
#define ID_CONTROL_STOPAFTERCURRENT     255
#define ID_FILE_FONT                    256
#define ID_PLAYLIST_OPEN                257
#define ID_PLAYLIST_SAVE                258
#define ID_ENTER                        259
#define ID_RATE_CUSTOM                  260
#define ID_JUMPTOTIME                   261
#define ID_REPEAT1                      262
#define ID_COLORS                       263
#define ID_CONTROL_PLAYPAUSE            264
#define ID_PASTE                        265
#define ID_PLAYLIST_REMOVEPREVIOUS      266
#define ID_TIMEREMAIN                   267
#define ID_ALLINFO                      268
#define ID_TOOLBAR                      269
#define ID_GRAB                         270
#define ID_VISUAL                       271
#define ID_SUBTITLES_FONT               272
#define ID_SUBTITLES_COLOR              273
#define ID_SUBTITLES_EARLIER            274
#define ID_SUBTITLES_LATER              275
#define ID_SUBTITLES_MOVEUP             276
#define ID_SUBTITLES_MOVEDOWN           277
#define ID_FILEINFO                     278
#define ID_SUBTITLES_LOAD               279
#define ID_SUBTITLES_LARGER             280
#define ID_SUBTITLES_SMALLER            281
#define ID_DDCOLOR                      282
#define ID_SUBTITLES_OFF                283
#define ID_SUBTITLES_TIMECORRECTION     284
#define ID_AUDIOSTREAM                  285
#define ID_KEYS                         286
#define ID_OPENURL                      287
#define ID_PLAYLIST_CROP                288
#define ID_RATE_75                      289
#define ID_RATE_125                     290
#define ID_CDINFO                       293
#define ID_NEXTVISUAL                   294
#define ID_PLAYAUDIOCD                  295
#define ID_DELETE_FILE                  296
#define ID_EQUALIZER                    297
#define ID_RATIO_SCREEN                 298
#define ID_DVD_FILE_OPENDVD             299
#define ID_DVD_MENU_RESUME              302
#define ID_DVD_NEXTCHAPTER              303
#define ID_DVD_PREVIOUSCHAPTER          304
#define ID_DVD_REPLAYCHAPTER            305
#define ID_DVD_SHOWCC                   306
#define ID_DVD_SHOWSUBPICTURE           307
#define ID_DVD_MENU_ROOT                308
#define ID_DVD_MENU_SUBPICTURE          309
#define ID_DVD_MENU_AUDIO               310
#define ID_DVD_MENU_ANGLE               311
#define ID_DVD_MENU_CHAPTER             312
#define ID_DVD_MENU_TITLE               313
#define IDC_SFPS                        511
#define IDC_SEXT                        512
#define IDC_SASSOC                      513
#define IDC_SDSTRACK_PREBUF             514
#define IDC_STIMEUPDATE                 515
#define IDC_FULLSCREEN                  516
#define IDC_STARTFOREGROUND             517
#define IDC_SVISPRIORITY                518
#define IDC_PRIORITY                    519
#define IDC_SORTONLOAD                  520
#define IDC_SDSPREBUF                   521
#define IDC_SJUMP                       522
#define IDC_SSECOND                     523
#define IDC_KEEP_RATIO                  524
#define IDC_USEDEVICE                   525
#define IDC_USEDS                       526
#define IDC_FADEOUT_PAUSE               528
#define IDC_FADEOUT_STOP                529
#define IDC_FADEOUT_SEEK                530
#define IDC_SVISTIMER                   531
#define IDC_DSNOTIF0                    532
#define IDC_DSNOTIF1                    533
#define IDC_SSUBTDELAY                  534
#define IDC_SDSNOTIF_POS                535
#define IDC_SUBTOUTLINE                 536
#define IDC_SSUBTSHIFT                  537
#define IDC_SEQ_FREQ                    538
#define IDC_ENABLE_EQ                   538
#define IDC_SSUBTSCALE                  539
#define IDC_CDDA                        541
#define IDC_SSUBTHELP1                  542
#define IDC_SSUBTHELP2                  543
#define IDC_SSUBTHELP3                  544
#define IDC_SSUBTHELP4                  545
#define IDC_USEOVERLAY                  546
#define IDC_SUBTAUTOLOAD                547
#define IDC_SCDMETHOD                   548
#define IDC_CDSWAPLR                    549
#define IDC_SUBTCOLOR                   550
#define IDC_SUBTFONT                    551
#define IDC_CDBIGENDIAN                 552
#define IDC_SSUBTDIR                    553
#define IDC_GAPLESS                     554
#define IDC_SOVERLAP                    555
#define IDC_SCDSPEED                    556
#define IDC_SUBTOPAQUE                  557
#define IDC_FULLSCREENRATIO             558
#define IDC_SDSBUFLEN                   559
#define IDC_SCDSECTORS                  560
#define IDC_CDTEXT_ON                   561
#define IDC_SOPENDIR_FOLDER             562
#define IDC_SCOLUMNS                    563
#define IDC_ISO88591                    564
#define IDC_SCOLUMNS_HELP               565
#define IDC_SCMD                        566
#define IDC_SKEY                        567
#define IDC_SFADE                       568
#define IDC_SVOLUME                     569
#define IDC_VOLUME0                     570
#define IDC_VOLUME1                     571
#define IDC_VOLUME2                     572
#define IDC_SSUBTEXT                    574
#define IDC_MULTINST                    575
#define IDC_REGEXT                      576
#define IDC_UNDERSCORES                 577
#define IDC_AUTOINFO                    578
#define IDC_SCREENSAVER                 579
#define IDC_COLOR_PLAYLIST              580
#define IDC_COLOR_SELECTED              581
#define IDC_COLOR_PLAYING               582
#define IDC_COLOR_PROGRESS              583
#define IDC_COLOR_TOOLBAR               584
#define IDC_COLOR_TIME                  585
#define IDC_COLOR_SUBT                  586
#define IDC_SRATE                       590
#define IDC_SSAVEDLIST                  591
#define IDS_TITLE                       592
#define IDC_HIDE_MOUSE                  593
#define IDC_SETCDSPEED                  594
#define IDC_USEOVERLAY0                 595
#define IDC_USEOVERLAY1                 596
#define IDC_USEOVERLAY2                 597
#define IDC_SFOLDER                     600
#define IDC_CDDBWIN                     601
#define IDC_CDDBUNIX                    602
#define IDC_CDDBACP                     603
#define IDC_CDDBUTF8                    604
#define IDC_SSERVER                     606
#define IDC_SPORT                       607
#define IDC_SEMAIL                      608
#define IDC_USEPROXY                    609
#define IDC_SALBUM                      610
#define IDC_SARTIST                     611
#define IDC_SCOMMENT                    612
#define IDC_SYEAR                       613
#define IDC_SGENRE                      614
#define IDC_SFREEDB                     615
#define IDC_CDSAVELOCAL                 616
#define IDC_CDREADLOCAL                 617
#define IDC_QUERY_FREEDB                618
#define IDC_SUBMIT                      619
#define IDC_SSECTOR                     625
#define IDC_DSCHECK_UNDERRUN            626
#define IDC_CDDELLOCAL                  630
#define IDC_SFREEDB_COLLISION           631
#define IDC_SENCODING                   632
#define IDC_SFORMAT                     633
#define IDC_AUTO_CONNECT                634
#define IDC_SPATH                       635
#define IDC_SHOWSITELIST                636
#define IDC_SITES                       637
#define IDC_SPLAYORDER                  638
#define IDC_CDUSEORDER                  639
#define IDC_SUSER                       640
#define IDC_SPASSWD                     641
#define IDC_STIMEOUT                    642
#define IDC_SSEC                        643
#define IDC_CDDELETE                    644
#define IDC_SREVISION                   646
#define IDC_STOTAL                      647
#define IDC_CDTEXT                      648
#define IDC_DDCOLOR_RESET               684
#define IDC_SBRIGHTNESS                 685
#define IDC_SCONTRAST                   686
#define IDC_SSATURATION                 687
#define IDC_SHUE                        688
#define IDC_SGAMMA                      689
#define IDC_DS_SSAMPLE_SIZE             903
#define IDC_DS_SBUFFERED                904
#define IDC_DS_SFORMAT                  915
#define IDC_DS_SUNDERRUN                916
#define IDC_DS_SLOCKS                   917
#define ID_SUBTITLES                    1098
#define ID_FILTERS                      1100
#define ID_DVD_SUBPICTURE_BASE          41000
#define ID_DVD_SUBPICTURE_MAX           41019
#define ID_DVD_AUDIO_BASE               41020
#define ID_DVD_AUDIO_MAX                41039
#define ID_DVD_ANGLE_BASE               41040
#define ID_DVD_ANGLE_MAX                41059
#define ID_DVD_TITLE_BASE               41100
#define ID_DVD_TITLE_MAX                41159
#define ID_DVD_CHAPTER_BASE             42000
#define ID_DVD_CHAPTER_MAX              42059
#define ID_DVD_MENULANG_BASE            42100
#define ID_DVD_MENULANG_MAX             42159
#define ID_FILE_NEXT_NOPLAY             42200
#define ID_FILE_PREVIOUS_NOPLAY         42201
#define ID_FILE_PAUSE_NOPLAY            42202
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         313
#define _APS_NEXT_CONTROL_VALUE         687
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
